exports.config = {
  runner: 'local',
  port: 4723,
  path: '/wd/hub',
  specs: ['./tests/**/*.spec.js'],
  exclude: [],
  maxInstances: 1,
  capabilities: [
    {
      maxInstances: 1,
      browserName: '',
      acceptInsecureCerts: true,
      'appium:platformName': 'Android',
      'appium:automationName': 'UiAutomator2',
      'appium:deviceName': 'Android Emulator',
      'appium:platformVersion': '13.0',
      'appium:app': './android/app/build/outputs/apk/debug/app-debug.apk',
      'appium:noReset': true,
    },
  ],
  logLevel: 'info',
  bail: 0,
  baseUrl: 'http://localhost',
  waitforTimeout: 10000,
  connectionRetryTimeout: 120000,
  connectionRetryCount: 3,
  services: ['appium'],
  framework: 'mocha',
  reporters: ['spec'],
  mochaOpts: {
    ui: 'bdd',
    timeout: 60000,
  },
};
